const log = require('debug')('utils:getGatherData');
const fs = require('fs');
const path = require('path');


/**
 * Get metadata for a sample, as generated by gather
 * @param {string} runName - name of the run/folder
 * @return {object} - object with key: value metadata from gather
 */
function getGatherData(runName) {
    // it's just a tsv
    // return as  { [key: string]: string }[]
    // probably only one row from what I can see, but leave room
    if (!runName || !process.env.SAMPLES_DIR) {
        log(`runName or SAMPLES_DIR not set, received ${runName} and ${process.env.SAMPLES_DIR}`);
        return null;
    }
    const gatherFile = path.join(
        process.env.SAMPLES_DIR,
        runName,
        'main',
        'gather',
        runName + '-meta.tsv',
    );
    if (!fs.existsSync(gatherFile)) {
        log(`Could not find gather file ${gatherFile}`);
        return null;
    }
    const gatherData = fs.readFileSync(gatherFile, 'utf8');
    // parse as tsv file
    const gatherDataObj = [];
    const lines = gatherData.split('\n');
    const headers = lines[0].split('\t');
    lines.slice(1).forEach((line) => {
        const row = line.split('\t');
        const obj = {};
        let empty = true;
        headers.forEach((header, i) => {
            obj[header] = row[i];
            if (row[i]) {
                empty = false;
            }
        });
        // if still empty, remove the key from obj
        if (!empty) {
            gatherDataObj.push(obj);
        }
    });
    return gatherDataObj?.[0];
}

module.exports = getGatherData;
